----DROP TABLE IF EXISTS records;
----DROP TABLE IF EXISTS users;
--CREATE TABLE records(id serial PRIMARY KEY, login VARCHAR(255), password VARCHAR(255));
----CREATE TABLE users(id serial PRIMARY KEY, login VARCHAR(255));